args:
  Code: Energy
  affinity_pre: true
  angle_feat_size: 0
  attention_dropout_rate: 0.1
  attention_kd: 0
  attention_mask: true
  batch_size: 1
  checkpoint: ./
  clip: 5.0
  complex_to_data: !!python/name:interformer.feats.gnina_types.gnina_featurizer.obabel_mol_parser ''
  data_path: interformer/train/general_PL_2020.csv
  dataset: sbdd
  debug: false
  dropout_rate: 0.1
  early_stop_metric: val_loss
  early_stop_mode: min
  edge_feat_size: 1
  edge_featurizer: !!python/object:interformer.feats.gnina_types.gnina_featurizer.PLIPEdgeFeaturizer
    covalent_bond: false
    feat_dim: 1
    interaction_angle: false
    plip_edge_feat_index:
    - 'no'
    - hbond
    - saltbridge
    - halogenbond
    - pication
    - pistack
    - hydroph_interaction
    plip_node_feat_index:
    - HACC
    - HDON
    - PISTACK
    - PICATION_RING
    - PICATION_POS
    - PICATION_NEG
    - HYDROPH
    - SALT_POS
    - SALT_NEG
    - XBOND_ACC
    - XBOND_DON
  edge_output_layer: true
  end_lr: 1.0e-09
  energy_mode: true
  energy_output_folder: ''
  ensemble:
  - checkpoint
  exp: Interformer_Gnina2
  ffn_scale: 4
  filter_type: normal
  gpus: 4
  hidden_dim: 128
  inference: false
  inter_encoder: true
  intput_dropout_rate: 0.0
  intra_encoder: true
  jizhi: false
  ligand_folder: ligand/rcsb
  main_loop: 1
  method: Gnina2
  metric_name:
  - r
  model: Interformer
  n_jobs: 70
  n_layers: 6
  native_sampler: 0
  neg_weight: 1.0
  node_feat_size: 1
  node_featurizer: !!python/object:interformer.feats.gnina_types.gnina_featurizer.PLIPAtomFeaturizer
    amino_type: false
    atom_equivalence_data:
    - !!python/tuple
      - Se
      - S
    atom_type_data:
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.02
      ad_heteroatom: false
      ad_radius: 1.0
      ad_solvation: 0.00051
      ad_volume: 0.0
      adname: H
      anum: 1
      covalent_radius: 0.37
      sm: Hydrogen
      smina_name: Hydrogen
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 0.0
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.02
      ad_heteroatom: false
      ad_radius: 1.0
      ad_solvation: 0.00051
      ad_volume: 0.0
      adname: HD
      anum: 1
      covalent_radius: 0.37
      sm: PolarHydrogen
      smina_name: PolarHydrogen
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 0.0
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.15
      ad_heteroatom: false
      ad_radius: 2.0
      ad_solvation: -0.00143
      ad_volume: 33.5103
      adname: C
      anum: 6
      covalent_radius: 0.77
      sm: AliphaticCarbonXSHydrophobe
      smina_name: AliphaticCarbonXSHydrophobe
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 1.9
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.15
      ad_heteroatom: false
      ad_radius: 2.0
      ad_solvation: -0.00143
      ad_volume: 33.5103
      adname: C
      anum: 6
      covalent_radius: 0.77
      sm: AliphaticCarbonXSNonHydrophobe
      smina_name: AliphaticCarbonXSNonHydrophobe
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 1.9
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.15
      ad_heteroatom: false
      ad_radius: 2.0
      ad_solvation: -0.00052
      ad_volume: 33.5103
      adname: A
      anum: 6
      covalent_radius: 0.77
      sm: AromaticCarbonXSHydrophobe
      smina_name: AromaticCarbonXSHydrophobe
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 1.9
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.15
      ad_heteroatom: false
      ad_radius: 2.0
      ad_solvation: -0.00052
      ad_volume: 33.5103
      adname: A
      anum: 6
      covalent_radius: 0.77
      sm: AromaticCarbonXSNonHydrophobe
      smina_name: AromaticCarbonXSNonHydrophobe
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 1.9
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.16
      ad_heteroatom: true
      ad_radius: 1.75
      ad_solvation: -0.00162
      ad_volume: 22.4493
      adname: N
      anum: 7
      covalent_radius: 0.75
      sm: Nitrogen
      smina_name: Nitrogen
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 1.8
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.16
      ad_heteroatom: true
      ad_radius: 1.75
      ad_solvation: -0.00162
      ad_volume: 22.4493
      adname: N
      anum: 7
      covalent_radius: 0.75
      sm: NitrogenXSDonor
      smina_name: NitrogenXSDonor
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.8
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.16
      ad_heteroatom: true
      ad_radius: 1.75
      ad_solvation: -0.00162
      ad_volume: 22.4493
      adname: NA
      anum: 7
      covalent_radius: 0.75
      sm: NitrogenXSDonorAcceptor
      smina_name: NitrogenXSDonorAcceptor
      xs_acceptor: true
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.8
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.16
      ad_heteroatom: true
      ad_radius: 1.75
      ad_solvation: -0.00162
      ad_volume: 22.4493
      adname: NA
      anum: 7
      covalent_radius: 0.75
      sm: NitrogenXSAcceptor
      smina_name: NitrogenXSAcceptor
      xs_acceptor: true
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 1.8
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 1.6
      ad_solvation: -0.00251
      ad_volume: 17.1573
      adname: O
      anum: 8
      covalent_radius: 0.73
      sm: Oxygen
      smina_name: Oxygen
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 1.7
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 1.6
      ad_solvation: -0.00251
      ad_volume: 17.1573
      adname: O
      anum: 8
      covalent_radius: 0.73
      sm: OxygenXSDonor
      smina_name: OxygenXSDonor
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.7
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 1.6
      ad_solvation: -0.00251
      ad_volume: 17.1573
      adname: OA
      anum: 8
      covalent_radius: 0.73
      sm: OxygenXSDonorAcceptor
      smina_name: OxygenXSDonorAcceptor
      xs_acceptor: true
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.7
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 1.6
      ad_solvation: -0.00251
      ad_volume: 17.1573
      adname: OA
      anum: 8
      covalent_radius: 0.73
      sm: OxygenXSAcceptor
      smina_name: OxygenXSAcceptor
      xs_acceptor: true
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 1.7
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 2.0
      ad_solvation: -0.00214
      ad_volume: 33.5103
      adname: S
      anum: 16
      covalent_radius: 1.02
      sm: Sulfur
      smina_name: Sulfur
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 2.0
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 2.0
      ad_solvation: -0.00214
      ad_volume: 33.5103
      adname: SA
      anum: 16
      covalent_radius: 1.02
      sm: SulfurAcceptor
      smina_name: SulfurAcceptor
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 2.0
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.2
      ad_heteroatom: true
      ad_radius: 2.1
      ad_solvation: -0.0011
      ad_volume: 38.7924
      adname: P
      anum: 15
      covalent_radius: 1.06
      sm: Phosphorus
      smina_name: Phosphorus
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: false
      xs_radius: 2.1
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.08
      ad_heteroatom: true
      ad_radius: 1.545
      ad_solvation: -0.0011
      ad_volume: 15.448
      adname: F
      anum: 9
      covalent_radius: 0.71
      sm: Fluorine
      smina_name: Fluorine
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 1.5
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.276
      ad_heteroatom: true
      ad_radius: 2.045
      ad_solvation: -0.0011
      ad_volume: 35.8235
      adname: Cl
      anum: 17
      covalent_radius: 0.99
      sm: Chlorine
      smina_name: Chlorine
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 1.8
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.389
      ad_heteroatom: true
      ad_radius: 2.165
      ad_solvation: -0.0011
      ad_volume: 42.5661
      adname: Br
      anum: 35
      covalent_radius: 1.14
      sm: Bromine
      smina_name: Bromine
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 2.0
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.55
      ad_heteroatom: true
      ad_radius: 2.36
      ad_solvation: -0.0011
      ad_volume: 55.0585
      adname: I
      anum: 53
      covalent_radius: 1.33
      sm: Iodine
      smina_name: Iodine
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 2.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.875
      ad_heteroatom: true
      ad_radius: 0.65
      ad_solvation: -0.0011
      ad_volume: 1.56
      adname: Mg
      anum: 12
      covalent_radius: 1.3
      sm: Magnesium
      smina_name: Magnesium
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.875
      ad_heteroatom: true
      ad_radius: 0.65
      ad_solvation: -0.0011
      ad_volume: 2.14
      adname: Mn
      anum: 25
      covalent_radius: 1.39
      sm: Manganese
      smina_name: Manganese
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.55
      ad_heteroatom: true
      ad_radius: 0.74
      ad_solvation: -0.0011
      ad_volume: 1.7
      adname: Zn
      anum: 30
      covalent_radius: 1.31
      sm: Zinc
      smina_name: Zinc
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.55
      ad_heteroatom: true
      ad_radius: 0.99
      ad_solvation: -0.0011
      ad_volume: 2.77
      adname: Ca
      anum: 20
      covalent_radius: 1.74
      sm: Calcium
      smina_name: Calcium
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.01
      ad_heteroatom: true
      ad_radius: 0.65
      ad_solvation: -0.0011
      ad_volume: 1.84
      adname: Fe
      anum: 26
      covalent_radius: 1.25
      sm: Iron
      smina_name: Iron
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.0
      ad_heteroatom: true
      ad_radius: 1.2
      ad_solvation: -0.0011
      ad_volume: 22.4493
      adname: M
      anum: 0
      covalent_radius: 1.75
      sm: GenericMetal
      smina_name: GenericMetal
      xs_acceptor: false
      xs_donor: true
      xs_hydrophobe: false
      xs_radius: 1.2
    - !!python/object:interformer.feats.gnina_types.gnina_featurizer.Info
      ad_depth: 0.18
      ad_heteroatom: false
      ad_radius: 2.04
      ad_solvation: -0.0011
      ad_volume: 12.052
      adname: B
      anum: 5
      covalent_radius: 0.9
      sm: Boron
      smina_name: Boron
      xs_acceptor: false
      xs_donor: false
      xs_hydrophobe: true
      xs_radius: 1.92
    atom_types:
    - Empty Atom
    - Hydrogen
    - PolarHydrogen
    - AliphaticCarbonXSHydrophobe
    - AliphaticCarbonXSNonHydrophobe
    - AromaticCarbonXSHydrophobe
    - AromaticCarbonXSNonHydrophobe
    - Nitrogen
    - NitrogenXSDonor
    - NitrogenXSDonorAcceptor
    - NitrogenXSAcceptor
    - Oxygen
    - OxygenXSDonor
    - OxygenXSDonorAcceptor
    - OxygenXSAcceptor
    - Sulfur
    - SulfurAcceptor
    - Phosphorus
    - Fluorine
    - Chlorine
    - Bromine
    - Iodine
    - Magnesium
    - Manganese
    - Zinc
    - Calcium
    - Iron
    - GenericMetal
    - Boron
    non_ad_metal_names:
    - Cu
    - Fe
    - Na
    - K
    - Hg
    - Co
    - U
    - Cd
    - Ni
    - Si
    plip_feat: false
    type_map:
      0: 10
      1: 10
      2: 0
      3: 1
      4: 2
      5: 3
      6: 4
      7: 5
      8: 5
      9: 4
      10: 6
      11: 7
      12: 7
      13: 6
      14: 8
      15: 8
      16: 9
      17: 10
      18: 10
      19: 10
      20: 10
      21: 10
      22: 10
      23: 10
      24: 10
      25: 10
      26: 10
      27: 10
  num_epochs: 2000
  num_ff_mols: 1
  num_gpus: 8
  num_heads: 8
  num_nodes: 1
  patience: 30
  peak_lr: 0.00012
  per_target: false
  per_target_sampler: 0
  pocket_path: pocket
  pose_sel_mode: false
  posfix: '*val_loss*'
  precision: 16
  rbf_K: 128
  rbf_cutoff: 10.0
  reload: true
  seed: 1111
  split_folder: diffdock_splits
  target_wise_sampler: 0
  test_csv:
  - ./test.csv
  uff_as_ligand: false
  use_ff_ligands: uff
  use_mid: false
  warmup_updates: 110000
  weight_decay: 1.0e-05
  work_path: interformer/poses
  worker: 8
